"""empty message

Revision ID: dae2fe3ba6fd
Revises: 879d807e7b99
Create Date: 2024-12-05 11:35:03.538123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae2fe3ba6fd'
down_revision = '879d807e7b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amico_CCT', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('amico_accessories', schema=None) as batch_op:
        batch_op.drop_constraint('amico_accessories_options_key', type_='unique')

    with op.batch_alter_table('amico_diffuser', schema=None) as batch_op:
        batch_op.drop_constraint('amico_diffuser_diffuser_key', type_='unique')

    with op.batch_alter_table('amico_doorframe', schema=None) as batch_op:
        batch_op.drop_constraint('amico_doorframe_doorframe_key', type_='unique')

    with op.batch_alter_table('amico_driver', schema=None) as batch_op:
        batch_op.drop_constraint('amico_driver_driver_key', type_='unique')

    with op.batch_alter_table('amico_function', schema=None) as batch_op:
        batch_op.drop_constraint('amico_lamp_lamp_key', type_='unique')

    with op.batch_alter_table('amico_model', schema=None) as batch_op:
        batch_op.drop_constraint('amico_model_model_key', type_='unique')

    with op.batch_alter_table('amico_mounting', schema=None) as batch_op:
        batch_op.drop_constraint('amico_mounting_mounting_key', type_='unique')

    with op.batch_alter_table('amico_options', schema=None) as batch_op:
        batch_op.drop_constraint('amico_options_options_key', type_='unique')

    with op.batch_alter_table('amico_switch', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('amico_voltage', schema=None) as batch_op:
        batch_op.drop_constraint('amico_voltage_voltage_key', type_='unique')

    with op.batch_alter_table('kenall_accessories', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_accessories_ref')

    with op.batch_alter_table('kenall_diffuser', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_diffuser_ref')

    with op.batch_alter_table('kenall_doorframe', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_doorframe_ref')

    with op.batch_alter_table('kenall_driver', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_driver_ref')
        batch_op.drop_constraint('amico_driver_ref', type_='foreignkey')
        batch_op.create_foreign_key(None, 'amico_driver', ['amico_id'], ['id'])

    with op.batch_alter_table('kenall_lamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diffuser', sa.String(), nullable=False))
        batch_op.alter_column('amico_id_CCT',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('fki_amico_CCT_ref')
        batch_op.drop_index('fki_amico_function_ref')
        batch_op.drop_index('fki_amico_lamp_ref')
        batch_op.drop_constraint('amico_CCT_ref', type_='foreignkey')
        batch_op.create_foreign_key(None, 'amico_CCT', ['amico_id_CCT'], ['id'])
        batch_op.drop_column('lamp')

    with op.batch_alter_table('kenall_model', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_model_ref')
        batch_op.drop_constraint('amico_model_ref', type_='foreignkey')
        batch_op.create_foreign_key(None, 'amico_model', ['amico_id'], ['id'])

    with op.batch_alter_table('kenall_mounting', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_mounting_ref')
        batch_op.drop_constraint('amico_mounting_ref', type_='foreignkey')
        batch_op.create_foreign_key(None, 'amico_mounting', ['amico_id'], ['id'])

    with op.batch_alter_table('kenall_options', schema=None) as batch_op:
        batch_op.alter_column('amico_id_switch',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('fki_amico_option_ref')
        batch_op.drop_index('fki_amico_options_ref')
        batch_op.drop_index('fki_amico_switch_ref')

    with op.batch_alter_table('kenall_voltage', schema=None) as batch_op:
        batch_op.drop_index('fki_amico_voltage_ref')
        batch_op.drop_constraint('amico_voltage_ref', type_='foreignkey')
        batch_op.create_foreign_key(None, 'amico_voltage', ['amico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kenall_voltage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amico_voltage_ref', 'amico_voltage', ['id'], ['id'])
        batch_op.create_index('fki_amico_voltage_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_options', schema=None) as batch_op:
        batch_op.create_index('fki_amico_switch_ref', ['amico_id_switch'], unique=False)
        batch_op.create_index('fki_amico_options_ref', ['id'], unique=False)
        batch_op.create_index('fki_amico_option_ref', ['amico_id'], unique=False)
        batch_op.alter_column('amico_id_switch',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('kenall_mounting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amico_mounting_ref', 'amico_mounting', ['id'], ['id'])
        batch_op.create_index('fki_amico_mounting_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amico_model_ref', 'amico_model', ['id'], ['id'])
        batch_op.create_index('fki_amico_model_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_lamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lamp', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amico_CCT_ref', 'amico_CCT', ['id'], ['id'])
        batch_op.create_index('fki_amico_lamp_ref', ['amico_id'], unique=False)
        batch_op.create_index('fki_amico_function_ref', ['amico_id'], unique=False)
        batch_op.create_index('fki_amico_CCT_ref', ['id'], unique=False)
        batch_op.alter_column('amico_id_CCT',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('diffuser')

    with op.batch_alter_table('kenall_driver', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amico_driver_ref', 'amico_driver', ['id'], ['id'])
        batch_op.create_index('fki_amico_driver_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_doorframe', schema=None) as batch_op:
        batch_op.create_index('fki_amico_doorframe_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_diffuser', schema=None) as batch_op:
        batch_op.create_index('fki_amico_diffuser_ref', ['id'], unique=False)

    with op.batch_alter_table('kenall_accessories', schema=None) as batch_op:
        batch_op.create_index('fki_amico_accessories_ref', ['amico_id'], unique=False)

    with op.batch_alter_table('amico_voltage', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_voltage_voltage_key', ['voltage'])

    with op.batch_alter_table('amico_switch', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('amico_options', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_options_options_key', ['options'])

    with op.batch_alter_table('amico_mounting', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_mounting_mounting_key', ['mounting'])

    with op.batch_alter_table('amico_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_model_model_key', ['model'])

    with op.batch_alter_table('amico_function', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_lamp_lamp_key', ['function'])

    with op.batch_alter_table('amico_driver', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_driver_driver_key', ['driver'])

    with op.batch_alter_table('amico_doorframe', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_doorframe_doorframe_key', ['doorframe'])

    with op.batch_alter_table('amico_diffuser', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_diffuser_diffuser_key', ['diffuser'])

    with op.batch_alter_table('amico_accessories', schema=None) as batch_op:
        batch_op.create_unique_constraint('amico_accessories_options_key', ['options'])

    with op.batch_alter_table('amico_CCT', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
