"""drop amico.id dependency

Revision ID: db13f02a8c66
Revises: 6a17e2c87e13
Create Date: 2024-12-03 13:37:03.147773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db13f02a8c66'
down_revision = '6a17e2c87e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amico_accessories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('options')
    )
    op.create_table('amico_diffuser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diffuser', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diffuser')
    )
    op.create_table('amico_doorframe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doorframe', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doorframe')
    )
    op.create_table('amico_driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver')
    )
    op.create_table('amico_lamp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lamp')
    )
    op.create_table('amico_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('amico_mounting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mounting', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mounting')
    )
    op.create_table('amico_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('options')
    )
    op.create_table('amico_voltage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voltage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voltage')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kenall_voltage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_voltage_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_voltage_ref')

    with op.batch_alter_table('kenall_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_options_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_options_ref')

    with op.batch_alter_table('kenall_mounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_mounting_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_mounting_ref')

    with op.batch_alter_table('kenall_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_model_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_model_ref')

    with op.batch_alter_table('kenall_lamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_lamp_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_lamp_ref')

    with op.batch_alter_table('kenall_driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_driver_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_driver_ref')

    with op.batch_alter_table('kenall_doorframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_doorframe_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_doorframe_ref')

    with op.batch_alter_table('kenall_diffuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_diffuser_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_diffuser_ref')

    with op.batch_alter_table('kenall_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doorframe', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kenall_accessories_amico_id_fkey', 'amico', ['amico_id'], ['id'])
        batch_op.drop_column('amico_accessories_ref')
        batch_op.drop_column('accessories')

    op.create_table('amico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='amico_pkey'),
    sa.UniqueConstraint('part_number', name='amico_part_number_key')
    )
    op.drop_table('amico_voltage')
    op.drop_table('amico_options')
    op.drop_table('amico_mounting')
    op.drop_table('amico_model')
    op.drop_table('amico_lamp')
    op.drop_table('amico_driver')
    op.drop_table('amico_doorframe')
    op.drop_table('amico_diffuser')
    op.drop_table('amico_accessories')
    # ### end Alembic commands ###
