"""rename doorframe column to options

Revision ID: ec610b0542a5
Revises: db13f02a8c66
Create Date: 2024-12-03 14:52:38.597153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec610b0542a5'
down_revision = 'db13f02a8c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kenall_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessories', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('amico_accessories_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_accessories', ['amico_accessories_ref'], ['id'])
        batch_op.drop_column('doorframe')
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_diffuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_diffuser_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_diffuser', ['amico_diffuser_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_doorframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_doorframe_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_doorframe', ['amico_doorframe_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_driver_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_driver', ['amico_driver_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_lamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_lamp_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_lamp', ['amico_lamp_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_model_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_model', ['amico_model_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_mounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_mounting_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_mounting', ['amico_mounting_ref'], ['id'])
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('amico_options_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_options', ['amico_options_ref'], ['id'])
        batch_op.drop_column('doorframe')
        batch_op.drop_column('amico_id')

    with op.batch_alter_table('kenall_voltage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_voltage_ref', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'amico_voltage', ['amico_voltage_ref'], ['id'])
        batch_op.drop_column('amico_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kenall_voltage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_voltage_ref')

    with op.batch_alter_table('kenall_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('doorframe', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_options_ref')
        batch_op.drop_column('options')

    with op.batch_alter_table('kenall_mounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_mounting_ref')

    with op.batch_alter_table('kenall_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_model_ref')

    with op.batch_alter_table('kenall_lamp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_lamp_ref')

    with op.batch_alter_table('kenall_driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_driver_ref')

    with op.batch_alter_table('kenall_doorframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_doorframe_ref')

    with op.batch_alter_table('kenall_diffuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_diffuser_ref')

    with op.batch_alter_table('kenall_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('doorframe', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amico_accessories_ref')
        batch_op.drop_column('accessories')

    # ### end Alembic commands ###
